In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_train = pd.read_csv("trainnn.csv")

In [3]:
data_train.shape

(891, 12)

In [4]:
data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
total = data_train.isnull().sum().sort_values(ascending=False)
vv = ((data_train.isnull().sum()) / len(data_train)).sort_values(ascending=False)

In [6]:
vv

Cabin          0.771044
Age            0.198653
Embarked       0.002245
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
dtype: float64

In [7]:
data_train.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [9]:
data_train = data_train.drop(["Name","Cabin","PassengerId","Ticket","Age"], axis=1)

In [10]:
data_train.head(20)

    Survived  Pclass     Sex  SibSp  Parch     Fare Embarked
0          0       3    male      1      0   7.2500        S
1          1       1  female      1      0  71.2833        C
2          1       3  female      0      0   7.9250        S
3          1       1  female      1      0  53.1000        S
4          0       3    male      0      0   8.0500        S
5          0       3    male      0      0   8.4583        Q
6          0       1    male      0      0  51.8625        S
7          0       3    male      3      1  21.0750        S
8          1       3  female      0      2  11.1333        S
9          1       2  female      1      0  30.0708        C
10         1       3  female      1      1  16.7000        S
11         1       1  female      0      0  26.5500        S
12         0       3    male      0      0   8.0500        S
13         0       3    male      1      5  31.2750        S
14         0       3  female      0      0   7.8542        S
15         1       2  female      0      0  16.0000        S
16         0       3    male      4      1  29.1250        Q
17         1       2    male      0      0  13.0000        S
18         0       3  female      1      0  18.0000        S
19         1       3  female      0      0   7.2250        C

In [11]:
data_train = pd.get_dummies(data_train)

In [12]:
data_train

,Survived,Pclass,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,0,7.2500,0,1,0,0,1
1,1,1,1,0,71.2833,1,0,1,0,0
2,1,3,0,0,7.9250,1,0,0,0,1
3,1,1,1,0,53.1000,1,0,0,0,1
4,0,3,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,0,13.0000,0,1,0,0,1
887,1,1,0,0,30.0000,1,0,0,0,1
888,0,3,1,2,23.4500,1,0,0,0,1
889,1,1,0,0,30.0000,0,1,1,0,0
890,0,3,0,0,7.7500,0,1,0,1,0

In [30]:
data_train=data_train.fillna(data_train.mean())

In [31]:
data_train

,Survived,Pclass,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,0,7.2500,0,1,0,0,1
1,1,1,1,0,71.2833,1,0,1,0,0
2,1,3,0,0,7.9250,1,0,0,0,1
3,1,1,1,0,53.1000,1,0,0,0,1
4,0,3,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,0,13.0000,0,1,0,0,1
887,1,1,0,0,30.0000,1,0,0,0,1
888,0,3,1,2,23.4500,1,0,0,0,1
889,1,1,0,0,30.0000,0,1,1,0,0
890,0,3,0,0,7.7500,0,1,0,1,0

In [32]:
data_train.isnull().sum()

Survived      0
Pclass        0
SibSp         0
Parch         0
Fare          0
Sex_female    0
Sex_male      0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [33]:
x_train= data_train.drop(['Survived'], axis = 1)
y_train = data_train['Survived']

In [34]:

data_train

,Survived,Pclass,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,0,7.2500,0,1,0,0,1
1,1,1,1,0,71.2833,1,0,1,0,0
2,1,3,0,0,7.9250,1,0,0,0,1
3,1,1,1,0,53.1000,1,0,0,0,1
4,0,3,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,0,13.0000,0,1,0,0,1
887,1,1,0,0,30.0000,1,0,0,0,1
888,0,3,1,2,23.4500,1,0,0,0,1
889,1,1,0,0,30.0000,0,1,1,0,0
890,0,3,0,0,7.7500,0,1,0,1,0

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
lg = LogisticRegression()
lg.fit(x_train ,y_train )

C:\Users\El-Shenawy\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
lg.score(x_train ,y_train)

0.7968574635241302

In [41]:
data_test = pd.read_csv("testtt.csv")

In [42]:
data_test = data_test.drop(["Name","Cabin","PassengerId","Ticket","Age"], axis=1)
data_test = pd.get_dummies(data_test)

In [43]:
data_test =data_test.fillna(data_test.mean())

In [44]:
data_test

,Pclass,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,0,0,7.8292,0,1,0,1,0
1,3,1,0,7.0000,1,0,0,0,1
2,2,0,0,9.6875,0,1,0,1,0
3,3,0,0,8.6625,0,1,0,0,1
4,3,1,1,12.2875,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
413,3,0,0,8.0500,0,1,0,0,1
414,1,0,0,108.9000,1,0,1,0,0
415,3,0,0,7.2500,0,1,0,0,1
416,3,0,0,8.0500,0,1,0,0,1
417,3,1,1,22.3583,0,1,1,0,0

In [49]:
y_test=lg.predict(data_test)

In [50]:
y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
      dtype=int64)